# Generated by Django 5.0.3 on 2024-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyhouruser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
