# Generated by Django 5.0.3 on 2024-03-27 06:13

import beautifyme.salons.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('city', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Stara Zagora', 'Stara Zagora'), ('Pleven', 'Pleven'), ('Sliven', 'Sliven'), ('Dobrich', 'Dobrich'), ('Shumen', 'Shumen'), ('Pernik', 'Pernik'), ('Yambol', 'Yambol'), ('Haskovo', 'Haskovo'), ('Blagoevgrad', 'Blagoevgrad'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Gabrovo', 'Gabrovo'), ('Vratsa', 'Vratsa'), ('Kyustendil', 'Kyustendil'), ('Pazardzhik', 'Pazardzhik')], max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to=beautifyme.salons.models.salon_image_upload_path)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
