# Generated by Django 5.0.3 on 2024-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_remove_appointment_user_appointment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
